### ISSUE TITLE
2025.1 Dimensions do not compile.

### ISSUE THREAD

**Issue by Knightrage1502** [Spectrall368/Generator-1.18.2#6]
Here is what it does when I make a dimension. Also you are doing a great job with your generators just curious when the 1.15.2 generator will be updated.
Executing Gradle task: build 
Build info: MCreator 2025.1.10519, forge-1.18.2, 64-bit, 16310 MB, Windows 11, JVM 21.0.5, JAVA_HOME: C:\MCreator20251\jdk, started on: 2025-07-19-15:52:30 
 
Calculating task graph as no cached configuration is available for tasks: build 
> Task :jarJar NO-SOURCE 
> Task :processTestResources NO-SOURCE 
> Task :processResources 
> Task :createMinecraftArtifacts 
Loaded 120 artifacts from C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\build\tmp\createMinecraftArtifacts\nfrt_artifact_manifest.properties 
  WARNING: de.oceanlabs.mcp:mcp_config:1.18.2-20220404.173914@zip is not present in the artifact manifest 
DONE  Completed downloadJson in 0.02s 
REUSE Used cache of listLibraries in 0.00s 
DONE  Completed downloadServer in 0.03s 
DONE  Completed downloadClient in 0.03s 
DONE  Completed downloadClientMappings in 0.03s 
REUSE Used cache of mergeMappings in 0.00s 
REUSE Used cache of createMappings in 0.00s 
REUSE Used cache of stripClient in 0.00s 
REUSE Used cache of extractServer in 0.00s 
REUSE Used cache of stripServer in 0.00s 
REUSE Used cache of merge in 0.00s 
REUSE Used cache of rename in 0.00s 
REUSE Used cache of stripSideAnnotations in 0.00s 
REUSE Used cache of decompile in 0.00s 
REUSE Used cache of inject in 0.00s 
REUSE Used cache of patch in 0.00s 
REUSE Used cache of applyNeoforgePatches in 0.00s 
REUSE Used cache of transformSources in 0.00s 
REUSE Used cache of remapSrgSourcesToOfficial in 0.00s 
REUSE Used cache of recompile in 0.00s 
REUSE Used cache of sourcesAndCompiledWithNeoForge in 0.00s 
Total runtime: 0.94s 
> Task :compileJava 
[C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\init\OfabSpaceModBlocks.java:22](file:///C:/Users/lmnws/MCreatorWorkspaces/ofab_space%20-%20Copy/src/main/java/net/mcreator/ofabspace/init/OfabSpaceModBlocks.java:22): error: cannot find symbol 
    public static final RegistryObject<Block> THE_MOON_PORTAL = REGISTRY.register("the_moon_portal", () -> new TheMoonPortalBlock()); 
                                                                                                               ^ 
  symbol:   class TheMoonPortalBlock 
  location: class OfabSpaceModBlocks 
[C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\init\OfabSpaceModBlocks.java:23](file:///C:/Users/lmnws/MCreatorWorkspaces/ofab_space%20-%20Copy/src/main/java/net/mcreator/ofabspace/init/OfabSpaceModBlocks.java:23): error: cannot find symbol 
    public static final RegistryObject<Block> THE_MARS_PORTAL = REGISTRY.register("the_mars_portal", () -> new TheMarsPortalBlock()); 
                                                                                                               ^ 
  symbol:   class TheMarsPortalBlock 
  location: class OfabSpaceModBlocks 
[C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\init\OfabSpaceModBlocks.java:24](file:///C:/Users/lmnws/MCreatorWorkspaces/ofab_space%20-%20Copy/src/main/java/net/mcreator/ofabspace/init/OfabSpaceModBlocks.java:24): error: cannot find symbol 
    public static final RegistryObject<Block> THE_MERCURY_PORTAL = REGISTRY.register("the_mercury_portal", () -> new TheMercuryPortalBlock()); 
                                                                                                                     ^ 
  symbol:   class TheMercuryPortalBlock 
  location: class OfabSpaceModBlocks 
[C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\init\OfabSpaceModBlocks.java:25](file:///C:/Users/lmnws/MCreatorWorkspaces/ofab_space%20-%20Copy/src/main/java/net/mcreator/ofabspace/init/OfabSpaceModBlocks.java:25): error: cannot find symbol 
    public static final RegistryObject<Block> THE_VENUS_PORTAL = REGISTRY.register("the_venus_portal", () -> new TheVenusPortalBlock()); 
                                                                                                                 ^ 
  symbol:   class TheVenusPortalBlock 
  location: class OfabSpaceModBlocks 
[C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\init\OfabSpaceModBlocks.java:35](file:///C:/Users/lmnws/MCreatorWorkspaces/ofab_space%20-%20Copy/src/main/java/net/mcreator/ofabspace/init/OfabSpaceModBlocks.java:35): error: cannot find symbol 
            TheMoonPortalBlock.registerRenderLayer(); 
            ^ 
  symbol:   variable TheMoonPortalBlock 
  location: class BlocksClientSideHandler 
[C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\init\OfabSpaceModBlocks.java:36](file:///C:/Users/lmnws/MCreatorWorkspaces/ofab_space%20-%20Copy/src/main/java/net/mcreator/ofabspace/init/OfabSpaceModBlocks.java:36): error: cannot find symbol 
            TheMarsPortalBlock.registerRenderLayer(); 
            ^ 
  symbol:   variable TheMarsPortalBlock 
  location: class BlocksClientSideHandler 
[C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\init\OfabSpaceModBlocks.java:37](file:///C:/Users/lmnws/MCreatorWorkspaces/ofab_space%20-%20Copy/src/main/java/net/mcreator/ofabspace/init/OfabSpaceModBlocks.java:37): error: cannot find symbol 
            TheMercuryPortalBlock.registerRenderLayer(); 
            ^ 
  symbol:   variable TheMercuryPortalBlock 
  location: class BlocksClientSideHandler 
[C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\init\OfabSpaceModBlocks.java:38](file:///C:/Users/lmnws/MCreatorWorkspaces/ofab_space%20-%20Copy/src/main/java/net/mcreator/ofabspace/init/OfabSpaceModBlocks.java:38): error: cannot find symbol 
            TheVenusPortalBlock.registerRenderLayer(); 
            ^ 
  symbol:   variable TheVenusPortalBlock 
  location: class BlocksClientSideHandler 
[C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\init\OfabSpaceModItems.java:25](file:///C:/Users/lmnws/MCreatorWorkspaces/ofab_space%20-%20Copy/src/main/java/net/mcreator/ofabspace/init/OfabSpaceModItems.java:25): error: cannot find symbol 
    public static final RegistryObject<Item> THE_MOON = REGISTRY.register("the_moon", () -> new TheMoonItem()); 
                                                                                                ^ 
  symbol:   class TheMoonItem 
  location: class OfabSpaceModItems 
[C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\init\OfabSpaceModItems.java:26](file:///C:/Users/lmnws/MCreatorWorkspaces/ofab_space%20-%20Copy/src/main/java/net/mcreator/ofabspace/init/OfabSpaceModItems.java:26): error: cannot find symbol 
    public static final RegistryObject<Item> THE_MARS = REGISTRY.register("the_mars", () -> new TheMarsItem()); 
                                                                                                ^ 
  symbol:   class TheMarsItem 
  location: class OfabSpaceModItems 
[C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\init\OfabSpaceModItems.java:27](file:///C:/Users/lmnws/MCreatorWorkspaces/ofab_space%20-%20Copy/src/main/java/net/mcreator/ofabspace/init/OfabSpaceModItems.java:27): error: cannot find symbol 
    public static final RegistryObject<Item> THE_MERCURY = REGISTRY.register("the_mercury", () -> new TheMercuryItem()); 
                                                                                                      ^ 
  symbol:   class TheMercuryItem 
  location: class OfabSpaceModItems 
[C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\init\OfabSpaceModItems.java:28](file:///C:/Users/lmnws/MCreatorWorkspaces/ofab_space%20-%20Copy/src/main/java/net/mcreator/ofabspace/init/OfabSpaceModItems.java:28): error: cannot find symbol 
    public static final RegistryObject<Item> THE_VENUS = REGISTRY.register("the_venus", () -> new TheVenusItem()); 
                                                                                                  ^ 
  symbol:   class TheVenusItem 
  location: class OfabSpaceModItems 
C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\OfabSpaceMod.java:58: warning: [removal] ResourceLocation(String,String) in ResourceLocation has been deprecated and marked for removal 
    public static final SimpleChannel PACKET_HANDLER = NetworkRegistry.newSimpleChannel(new ResourceLocation(MODID, MODID), () -> PROTOCOL_VERSION, PROTOCOL_VERSION::equals, PROTOCOL_VERSION::equals); 
                                                                                        ^ 
C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\world\features\ores\LavaOreFeature.java:52: warning: [removal] ResourceLocation(String) in ResourceLocation has been deprecated and marked for removal 
    public static final Set<ResourceLocation> GENERATE_BIOMES = Set.of(new ResourceLocation("ofab_space:mercury"), new ResourceLocation("ofab_space:moon")); 
                                                                       ^ 
C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\world\features\ores\LavaOreFeature.java:52: warning: [removal] ResourceLocation(String) in ResourceLocation has been deprecated and marked for removal 
    public static final Set<ResourceLocation> GENERATE_BIOMES = Set.of(new ResourceLocation("ofab_space:mercury"), new ResourceLocation("ofab_space:moon")); 
                                                                                                                   ^ 
C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\world\features\ores\LavaOreFeature.java:72: warning: [removal] ResourceLocation(String) in ResourceLocation has been deprecated and marked for removal 
            Registry.register(Registry.RULE_TEST, new ResourceLocation("ofab_space:lava_ore_match"), CUSTOM_MATCH); 
                                                  ^ 
C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\world\features\ores\SundiniteOreFeature.java:54: warning: [removal] ResourceLocation(String) in ResourceLocation has been deprecated and marked for removal 
    public static final Set<ResourceLocation> GENERATE_BIOMES = Set.of(new ResourceLocation("ofab_space:mars"), new ResourceLocation("ofab_space:venus")); 
                                                                       ^ 
C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\world\features\ores\SundiniteOreFeature.java:54: warning: [removal] ResourceLocation(String) in ResourceLocation has been deprecated and marked for removal 
    public static final Set<ResourceLocation> GENERATE_BIOMES = Set.of(new ResourceLocation("ofab_space:mars"), new ResourceLocation("ofab_space:venus")); 
                                                                                                                ^ 
C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\world\features\ores\SundiniteOreFeature.java:74: warning: [removal] ResourceLocation(String) in ResourceLocation has been deprecated and marked for removal 
            Registry.register(Registry.RULE_TEST, new ResourceLocation("ofab_space:sundinite_ore_match"), CUSTOM_MATCH); 
                                                  ^ 
C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\world\features\ores\SundiniteOreFeature.java:78: warning: [removal] ResourceLocation(String) in ResourceLocation has been deprecated and marked for removal 
            return List.of(Blocks.RED_SANDSTONE, Blocks.RED_SAND).contains(blockstate.getBlock()) || Stream.of(BlockTags.create(new ResourceLocation("minecraft:sandstone"))).anyMatch(blockstate::is); 
                                                                                                                                ^ 
12 errors 
8 warnings 
> Task :compileJava FAILED 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler output below. 
[C:\Users\lmnws\MCreatorWorkspaces\ofab_space - Copy\src\main\java\net\mcreator\ofabspace\init\OfabSpaceModBlocks.java:22](file:///C:/Users/lmnws/MCreatorWorkspaces/ofab_space%20-%20Copy/src/main/java/net/mcreator/ofabspace/init/OfabSpaceModBlocks.java:22): error: cannot find symbol 
      public static final RegistryObject<Block> THE_MOON_PORTAL = REGISTRY.register("the_moon_portal", () -> new TheMoonPortalBlock()); 
                                                                                                                 ^ 
    symbol:   class TheMoonPortalBlock 
    location: class OfabSpaceModBlocks 
  12 errors 
  8 warnings 
* Try: 
> Check your code and dependencies to fix the compilation error(s) 
> Run with --scan to get full insights. 
BUILD FAILED in 5s 
3 actionable tasks: 3 executed 
Configuration cache entry stored. 
 
BUILD FAILED 
Task completed in 7 seconds

**Comment by Spectrall368** [comment]
@Knightrage1502 Could you attach a demo workspace?

**Comment by Knightrage1502** [comment]
How would I do that?

**Comment by Spectrall368** [comment]
> How would I do that?

either make a workspace that reproduces the error, or attach your own

**Comment by Knightrage1502** [comment]
https://drive.google.com/file/d/1YC6R9uu0ILuvK4bNpPuqIc_jbB4t_OZA/view?usp=drive_link

**Comment by Spectrall368** [comment]
> https://drive.google.com/file/d/1YC6R9uu0ILuvK4bNpPuqIc_jbB4t_OZA/view?usp=drive_link

this is just a texture

**Comment by Knightrage1502** [comment]
Oops sorry lol. https://drive.google.com/drive/folders/1Ju1j3tOUm690UnUZGZtM-7XTvoBn-_lD?usp=drive_link

**Comment by Spectrall368** [comment]
> Oops sorry lol. https://drive.google.com/drive/folders/1Ju1j3tOUm690UnUZGZtM-7XTvoBn-_lD?usp=drive_link

Are you using the latest plugin version and 2025.1 release?

**Comment by Spectrall368** [comment]
<img width="867" height="531" alt="Image" src="https://github.com/user-attachments/assets/90c1c1c7-869b-48ac-a4fb-33bcfd618879" />

**Comment by Spectrall368** [comment]
or try restarting the client again



> > Oops sorry lol. https://drive.google.com/drive/folders/1Ju1j3tOUm690UnUZGZtM-7XTvoBn-_lD?usp=drive_link
> 
> Are you using the latest plugin version and 2025.1 release?

**Comment by Knightrage1502** [comment]
I will try again and maybe removing gradle caches will help.
